{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  hosts:
  - "{{ .Values.virtualService.host }}"
  gateways:
  - "{{ .Values.virtualService.gateway }}"
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: "{{ .Values.virtualService.serviceName }}"
        port:
          number: {{ .Values.virtualService.servicePort }}
{{- end }}
